# Generated by Django 4.2.2 on 2023-06-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upisi',
            name='status',
            field=models.CharField(blank=True, choices=[('upis', 'upisan'), ('da', 'polozen'), ('ne', 'izgubio potpis')], default='upis', max_length=64, null=True),
        ),
    ]
